# Generated by Django 4.2.3 on 2024-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=1000, null=True)),
                ('Taken_at', models.DateTimeField(auto_now_add=True)),
                ('Nitrogen', models.PositiveIntegerField(null=True)),
                ('Phosphorus', models.PositiveIntegerField(null=True)),
                ('Potassium', models.PositiveIntegerField(null=True)),
                ('Temperature', models.CharField(max_length=1000, null=True)),
                ('Humidity', models.CharField(max_length=1000, null=True)),
                ('Soil_pH', models.CharField(max_length=1000, null=True)),
                ('Rainfall', models.CharField(max_length=1000, null=True)),
                ('Crop_supported', models.CharField(blank=True, max_length=1000)),
                ('Other', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-Taken_at'],
            },
        ),
    ]
